
package com.db.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MyWebService", targetNamespace = "http://ws.db.com/")
public interface MyWebService {


    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://ws.db.com/", className = "com.db.cis.client.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://ws.db.com/", className = "com.db.cis.client.SayResponse")
    public String say(
            @WebParam(name = "message", targetNamespace = "")
            String message);

}
