
package com.db.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "myWebService", targetNamespace = "http://ws.db.com/", wsdlLocation = "http://localhost:8080/jaxws-spring?wsdl")
public class MyWebService_Service
    extends Service
{

    private final static URL MYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWEBSERVICE_EXCEPTION;
    private final static QName MYWEBSERVICE_QNAME = new QName("http://ws.db.com/", "myWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8180/cistat-web/jaxws-spring?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWEBSERVICE_WSDL_LOCATION = url;
        MYWEBSERVICE_EXCEPTION = e;
    }

    public MyWebService_Service() {
        super(__getWsdlLocation(), MYWEBSERVICE_QNAME);
    }

    public MyWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebServicePort")
    public MyWebService getMyWebServicePort() {
        return super.getPort(new QName("http://ws.db.com/", "MyWebServicePort"), MyWebService.class);
    }

    private static URL __getWsdlLocation() {
        if (MYWEBSERVICE_EXCEPTION!= null) {
            throw MYWEBSERVICE_EXCEPTION;
        }
        return MYWEBSERVICE_WSDL_LOCATION;
    }

}
